name: Auto Assign to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Automatically add issues to the correct project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/data-altinn-no/projects/1
          github-token: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
