name: Epic 
description: Create a new epic 
labels: ["Epic", "status/draft"]
body:          
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Who, why and what. 
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Links to relevant resources, documentation of other issues, UX sketches, technical architecture/requirements.

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Related tasks

